server:
  port: 8081
spring:
  application:
    name: local-grpc-server
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/TradeSimulator
    username: root
    password: example
  h2:
    console:
      enabled: true
mybatis:
  mapper-locations: classpath:mappers/*xml
pagehelper:
  reasonable: false
  defaultCount: true