server:
  port: 8081
grpc:
  server:
    port: 9091
mybatis:
  mapper-locations: classpath:mappers/*xml
  configration:
    local-cache-scope: statement
pagehelper:
  reasonable: false
  defaultCount: true
spring:
  application:
    name: currency-grpc-server
  profiles:
    include: @activatedProperties@