server:
  port: 8080
mybatis:
  mapper-locations: classpath:mappers/*xml
  configration:
    local-cache-scope: statement
pagehelper:
  reasonable: false
  defaultCount: true
spring:
  profiles:
    include: @activatedProperties@