spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/TradeSimulator
    username: root
    password: example
  redisson:
    enable: true
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
      pool:
        max-active: 8
        max-wait: 3000
        max-idle: 8
        min-idle: 0
        timeout: 600