server:
  port: 8082
grpc:
  server:
    port: 9092
mybatis:
  mapper-locations: classpath:mappers/*xml
  configration:
    local-cache-scope: statement
pagehelper:
  reasonable: false
  defaultCount: true
spring:
  application:
    name: stock-grpc-server
  profiles:
    include: @activatedProperties@